/**
 * The Buy Me a Coffee ask, in one place because it is said in two.
 *
 * The floating widget on every page and the button on `/thanks` carry the
 * *same sentence* on purpose — it is the author's own wording and a reader who
 * meets it twice should not find it reworded the second time. Keeping it here
 * rather than in both components is what makes that true by construction
 * instead of by discipline.
 *
 * It also keeps the apostrophes out of JSX, where `you're` and `don't` would
 * each need escaping and would each be an opportunity to get the sentence
 * subtly wrong.
 */
export const support = {
  slug: "Wilielmus",
  url: "https://www.buymeacoffee.com/Wilielmus",
  /** The widget's own hover label. */
  description: "Support me on Buy me a coffee!",
  message:
    "Hope you find the software useful! If you do and you're feeling generous buy me coffee! (I don't drink coffee BTW)",
  /** Buy Me a Coffee's brand blue, from the snippet this was built from. */
  colour: "#5F7FFF",
} as const;

/**
 * The button image, generated by Buy Me a Coffee's button API.
 *
 * It is an **SVG**, which is why it is rendered with a plain `<img>` rather
 * than `next/image`: optimising a remote SVG needs `dangerouslyAllowSVG`, and
 * that flag exists to be feared — it would let this site's own origin serve
 * arbitrary SVG, which is a script-execution surface. An `<img>` pointed at a
 * third party's SVG is the safe direction: scripting is disabled in that
 * context by the image spec, and it stays on their origin.
 */
export const supportButton = {
  src:
    "https://img.buymeacoffee.com/button-api/?text=Buy me a coffee&emoji=☕" +
    `&slug=${support.slug}&button_colour=5F7FFF&font_colour=ffffff` +
    "&font_family=Cookie&outline_colour=000000&coffee_colour=FFDD00",
  width: 235,
  height: 50,
} as const;
